### ISSUE TITLE
triggered alert number format can be wrong eg. "Unique visitors increased more than 55.000000rom"

### ISSUE THREAD

**Issue by mattab** [piwik/plugin-CustomAlerts#20]
![triggered alerts bug](https://cloud.githubusercontent.com/assets/466765/10812489/90abf36c-7e7b-11e5-98c1-3574cb25632f.png)

The text is: `Unique visitors increased more than 55.000000rom 4787 to 5106` but one expected: `Unique visitors increased more than 5%: from 4787 to 5106`

**Comment by tsteur** [comment]
From the looks and quick test it's related to the translation keys `ValuePercentageIncreasedMoreThan` which contains `%1$s%` and now needs to be changed to `%1$s%%`

**Comment by tsteur** [comment]
@mattab can you try https://github.com/piwik/plugin-CustomAlerts/pull/21
