### ISSUE TITLE
Custom Alert email has one empty "Alert condition" column

### ISSUE THREAD

**Issue by mattab** [piwik/plugin-CustomAlerts#39]
See our custom alert emails:

![alert](https://cloud.githubusercontent.com/assets/466765/23729867/9f6911b2-0464-11e7-8483-b24fa30ec2c7.png)

There is an empty column for "Alert condition" which looks a bug?

**Comment by sgiehl** [comment]
This should not be a bug. If you choose a report for the alert that has an dimension. Like Visits to Conversion for a goal you can specify a additional report condition. This condition would be displayed in the empty "alert condition" in the emails.
We might check if any of the alerts has a condition and remove the field in the email if not...

**Comment by sgiehl** [comment]
@mattab  How to proceed? Close the issue or adjust according to my last suggestion?

**Comment by mattab** [comment]
>  We might check if any of the alerts has a condition and remove the field in the email if not...

Sounds good :+1:
