### ISSUE TITLE
Error with " History of triggered alerts"

### ISSUE THREAD

**Issue by gaumondp** [piwik/plugin-CustomAlerts#5]
Piwik 2.2.0
PHP 5.3.13 under Suse
Custom Alerts 0.1.17
No other plugins enabled that are not part of Core.

While clicking on "History of triggered alerts", I got:

A fatal error occurred
The following error just broke Piwik (v2.2.0):
Class 'Piwik\Period\Factory' not found
in
/stats/piwik/plugins/CustomAlerts/Controller.php line 278

**Comment by mattab** [comment]
Hi @gaumondp if you have any issue please open  new one
